version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      # replace with your preferred image
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - node/install-yarn
      - run: |
          yarn install
          yarn build

workflows:
    example-workflow:
      jobs:
        - node/test:
            pkg-manager: yarn 
        - build
